// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Sortech.Model_SqlServerDB
{
    public partial class CCodeInfo
    {
        /// <summary>
        /// 사업장코드
        /// </summary>
        public string CorpCd { get; set; }
        /// <summary>
        /// 그룹코드
        /// </summary>
        public string ManageCd { get; set; }
        /// <summary>
        /// 코드
        /// </summary>
        public string CodeCd { get; set; }
        /// <summary>
        /// 코드명
        /// </summary>
        public string CodeNm { get; set; }
        /// <summary>
        /// 문자1
        /// </summary>
        public string Codevar1 { get; set; }
        /// <summary>
        /// 문자2
        /// </summary>
        public string Codevar2 { get; set; }
        /// <summary>
        /// 숫자1
        /// </summary>
        public long? Codeint1 { get; set; }
        /// <summary>
        /// 숫자2
        /// </summary>
        public long? Codeint2 { get; set; }
        /// <summary>
        /// 사용여부(Y/N)
        /// </summary>
        public string User_yn { get; set; }
        /// <summary>
        /// 비고
        /// </summary>
        public string Bigo { get; set; }
    }
}