// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Sortech.Model_SqlServerDB
{
    public partial class CEmpInfo_proc
    {
        /// <summary>
        /// 사번
        /// </summary>
        public string Empid { get; set; }
        /// <summary>
        /// 로그인id
        /// </summary>
        public string Loginid { get; set; }
        public string Password { get; set; }
        /// <summary>
        /// 이름
        /// </summary>
        public string EmpNm { get; set; }
        /// <summary>
        /// 생년월일
        /// </summary>
        public DateTime? Birthday { get; set; }
        /// <summary>
        /// 부서코드
        /// </summary>
        public string Dept { get; set; }

        public string DeptNm { get; set; }
        
        /// <summary>
        /// 직급코드
        /// </summary>
        public string Grade { get; set; }

        public string GradeNm { get; set; }
        /// <summary>
        /// 퇴사여부(Y/N)
        /// </summary>
        public string Leave { get; set; }
    }
}