// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sortech.Model_SqlServerDB
{
    public partial class CGroupCodeInfo
    {
        /// <summary>
        /// 법인코드
        /// </summary>
        //public string CorpCd { get; set; }
        /// <summary>
        /// 코드그룹코드
        /// </summary>
        public string ManageCd { get; set; }
        /// <summary>
        /// 코드그룹명
        /// </summary>
        public string ManageNm { get; set; }
        public string User_yn { get; set; }
        /// <summary>
        /// 비고
        /// </summary>
        public string Bigo { get; set; }
    }
}