// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sortech.Model_SqlServerDB
{
    public partial class CMenuList
    {
        public int MenuId { get; set; }
        public int? ParentMenuId { get; set; }
        public string PageName { get; set; }
        public string MenuName { get; set; }
        public string IconName { get; set; }
    }
}