// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Sortech.Model_SqlServerDB
{
    public interface IRepository_MenuList
    {
        Task<List<CMenuList>> GetAllMenu();
    }
}