// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Sortech.Model_SqlServerDB
{
    public interface IRepository_GroupCodeInfo
    {
        // 전체 가져오기
        Task<List<CGroupCodeInfo>> SelectAll();

        //특정 값만 가져오기
        Task<List<CGroupCodeInfo>> Select(string manageCD);

        // 저장하기
        void Insert(CGroupCodeInfo groupCodeInfo);
        
        // 삭제하기
        void Delete(string manageCD);

        // 업데이트하기
        void Update(string manageCd, CGroupCodeInfo groupCodeInfo);
    }
}