// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Sortech.DBConn;

namespace Sortech.Model_SqlServerDB
{
    public class Repository_MenuList : IRepository_MenuList
    {
        private readonly sortech_SqlServerDB_Context DB;

        public Repository_MenuList(sortech_SqlServerDB_Context _DB)
        {
            DB = _DB;
        }

        public Task<List<CMenuList>> GetAllMenu()
        {
            return DB.MenuList.ToListAsync();
        }
    }
}