// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Sortech.Model_MariaDB
{
    public interface IRepository_M_Menulist
    {
        // 전체 가져오기
        List<M_Menulist> MenuCall_SQL();

        void Insert_SQL(M_Menulist menulist);

        // 삭제하기
        void Delete_SQL(M_Menulist menulist);

        void Update_SQL(M_Menulist menulist);
    }
}