// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Sortech.Model_MariaDB
{
    public interface IRepository_Menulist
    {
        // 전체 가져오기
        Task<List<Menulist>> MenuCall_SQL();
    }
}