// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;

namespace Sortech.Model_MariaDB
{
    public partial class M_Menulist
    {
        [Key]
        public int MenuId { get; set; }
        public int? ParentMenuId { get; set; }
        public string PageName { get; set; }
        public string MenuName { get; set; }
        public string Menu_Type { get; set; }
        public string Icon { get; set; }
        public string User_yn { get; set; }
        public int? Sort_No { get; set; }
        public string Leaf_Yn { get; set; }
        public string Class { get; set; }
    }
}