// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sortech.Model_MariaDB;
using Sortech.Model_SqlServerDB;

namespace Sortech.DBConn
{
    public partial class sortech_MariaDB_Context : DbContext
    {
        public sortech_MariaDB_Context()
        {
        }

        public sortech_MariaDB_Context(DbContextOptions<sortech_MariaDB_Context> options)
            : base(options)
        {
        }

        public virtual DbSet<M_Menulist> M_Menulist { get; set; }
        public virtual DbSet<Menulist> Menulist { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("utf8mb4_general_ci")
                .HasCharSet("utf8mb4");

            modelBuilder.Entity<M_Menulist>(entity =>
            {
                entity.HasKey(e => e.MenuId)
                    .HasName("PRIMARY");

                entity.ToTable("menulist");

                entity.Property(e => e.MenuId)
                    .HasColumnType("int(11)")
                    .ValueGeneratedNever();

                entity.Property(e => e.Icon).HasMaxLength(50);

                entity.Property(e => e.Leaf_Yn)
                    .HasMaxLength(1)
                    .HasColumnName("Leaf_YN");

                entity.Property(e => e.MenuName).HasMaxLength(50);

                entity.Property(e => e.Menu_Type)
                    .HasMaxLength(10)
                    .HasColumnName("Menu_Type");

                entity.Property(e => e.PageName).HasMaxLength(50);

                entity.Property(e => e.ParentMenuId).HasColumnType("int(11)");

                entity.Property(e => e.Sort_No)
                    .HasColumnType("int(11)")
                    .HasColumnName("Sort_No");

                entity.Property(e => e.User_yn)
                    .HasMaxLength(1)
                    .HasColumnName("User_yn");
            });

            // query 사용할때 추가
            modelBuilder.Entity<Menulist>().HasNoKey();
            modelBuilder.Entity<Menulist>().ToView(name: "Menulist");
            // query 사용할때 추가

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}